-- NetSentinel Database Schema Setup
-- Copy and paste this script into your Supabase SQL Editor and click "Run".

-- 1. Devices Table
CREATE TABLE IF NOT EXISTS public.devices (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    hostname TEXT NOT NULL,
    platform TEXT NOT NULL,
    architecture TEXT NOT NULL,
    ip_address TEXT NOT NULL,
    agent_version TEXT NOT NULL,
    status TEXT NOT NULL,
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Telemetry Table
CREATE TABLE IF NOT EXISTS public.telemetry (
    id TEXT PRIMARY KEY,
    device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    latency_ms DOUBLE PRECISION NOT NULL,
    packet_loss DOUBLE PRECISION NOT NULL,
    gateway_reachable BOOLEAN NOT NULL,
    internet_reachable BOOLEAN NOT NULL,
    dns_healthy BOOLEAN NOT NULL,
    tcp_healthy BOOLEAN NOT NULL,
    interface_errors INTEGER NOT NULL,
    interface_drops INTEGER NOT NULL
);

-- 3. Incidents Table
CREATE TABLE IF NOT EXISTS public.incidents (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    severity TEXT NOT NULL,
    status TEXT NOT NULL,
    likely_cause TEXT NOT NULL,
    confidence TEXT NOT NULL,
    evidence TEXT[] NOT NULL DEFAULT '{}',
    recommended_actions TEXT[] NOT NULL DEFAULT '{}',
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- 4. Alerts Table
CREATE TABLE IF NOT EXISTS public.alerts (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    current_value DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- 5. Metric Baselines Table
CREATE TABLE IF NOT EXISTS public.metric_baselines (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    metric TEXT NOT NULL,
    "window" TEXT NOT NULL,
    average DOUBLE PRECISION NOT NULL,
    median DOUBLE PRECISION NOT NULL,
    p95 DOUBLE PRECISION NOT NULL,
    stddev DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 6. Diagnostic Runs Table
CREATE TABLE IF NOT EXISTS public.diagnostic_runs (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    duration_ms INTEGER NOT NULL,
    health_score INTEGER NOT NULL,
    status TEXT NOT NULL,
    mode TEXT NOT NULL
);

-- 7. Diagnostic History Table (Brought from local SQLite to Supabase for multi-user isolation)
CREATE TABLE IF NOT EXISTS public.history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    score INTEGER NOT NULL,
    status TEXT NOT NULL,
    gateway_status TEXT NOT NULL,
    internet_status TEXT NOT NULL,
    dns_status TEXT NOT NULL,
    tcp_status TEXT NOT NULL,
    latency DOUBLE PRECISION NOT NULL,
    packet_loss DOUBLE PRECISION NOT NULL,
    is_demo BOOLEAN NOT NULL DEFAULT FALSE
);

-- --- Enable Row-Level Security (RLS) ---
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metric_baselines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diagnostic_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;

-- --- Row-Level Security Policies ---

-- 1. Devices Policies
CREATE POLICY "Users can access their own devices" 
    ON public.devices FOR ALL 
    USING (auth.uid() = user_id);

CREATE POLICY "Allow public/service device registration" 
    ON public.devices FOR INSERT 
    WITH CHECK (true); -- Shared enrollment allowed; backend checks verification token

-- 2. Incidents Policies
CREATE POLICY "Users can access their own incidents" 
    ON public.incidents FOR ALL 
    USING (auth.uid() = user_id);

-- 3. Alerts Policies
CREATE POLICY "Users can access their own alerts" 
    ON public.alerts FOR ALL 
    USING (auth.uid() = user_id);

-- 4. Metric Baselines Policies
CREATE POLICY "Users can access their own metric baselines" 
    ON public.metric_baselines FOR ALL 
    USING (auth.uid() = user_id);

-- 5. Diagnostic Runs Policies
CREATE POLICY "Users can access their own diagnostic runs" 
    ON public.diagnostic_runs FOR ALL 
    USING (auth.uid() = user_id);

-- 6. History Policies
CREATE POLICY "Users can access their own history" 
    ON public.history FOR ALL 
    USING (auth.uid() = user_id);

-- 7. Telemetry Policies (Linked through device owner check)
CREATE POLICY "Users can read telemetry of their own devices" 
    ON public.telemetry FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.devices 
        WHERE public.devices.id = public.telemetry.device_id AND public.devices.user_id = auth.uid()
    ));

CREATE POLICY "Allow agents/telemetry ingestion" 
    ON public.telemetry FOR INSERT 
    WITH CHECK (true); -- Ingest allowed; backend checks verification token

-- Enable Realtime for relevant tables (Optional, enables live updates)
ALTER PUBLICATION supabase_realtime ADD TABLE public.devices;
ALTER PUBLICATION supabase_realtime ADD TABLE public.incidents;
ALTER PUBLICATION supabase_realtime ADD TABLE public.telemetry;
