-- Migration 001: bring an already-provisioned project up to date.
-- Safe to run more than once. Apply in Supabase -> SQL Editor -> Run.
--
-- Fixes two gaps found in the production project on 2026-09-14:
--   1. The `history` table was never created, so diagnostic runs for
--      signed-in users silently failed to save (History page always empty).
--   2. The `is_backup_target` tag column for the Backup Readiness module.

-- 1. History table (mirrors supabase_schema.sql section 7)
CREATE TABLE IF NOT EXISTS public.history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    score INTEGER NOT NULL,
    status TEXT NOT NULL,
    gateway_status TEXT NOT NULL,
    internet_status TEXT NOT NULL,
    dns_status TEXT NOT NULL,
    tcp_status TEXT NOT NULL,
    latency DOUBLE PRECISION NOT NULL,
    packet_loss DOUBLE PRECISION NOT NULL,
    is_demo BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'history'
          AND policyname = 'Users can access their own history'
    ) THEN
        CREATE POLICY "Users can access their own history"
            ON public.history FOR ALL
            USING (auth.uid() = user_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS history_user_id_timestamp_idx
    ON public.history (user_id, timestamp DESC);

-- 2. Backup-target tag on devices
ALTER TABLE public.devices
    ADD COLUMN IF NOT EXISTS is_backup_target BOOLEAN NOT NULL DEFAULT FALSE;
